In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
df.shape

(8128, 5)

In [4]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [5]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,Y_train,Y_test= train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2)
X_train.head(5)

              brand  km_driven    fuel         owner
5891        Hyundai      42130  Petrol   First Owner
229          Nissan      37000  Petrol   First Owner
1432       Mahindra     100000  Diesel  Second Owner
2704  Mercedes-Benz      10000  Diesel  Second Owner
3063          Honda     110000  Petrol   First Owner

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32,handle_unknown='ignore')

In [23]:
X_train_new=ohe.fit_transform(X_train)

In [24]:
X_test.head()

         brand  km_driven    fuel         owner
3522    Maruti      58343  Petrol   First Owner
6456    Jaguar      70000  Diesel  Second Owner
5130   Hyundai      27000  Diesel  Second Owner
6940  Mahindra      90000  Diesel   First Owner
7203    Maruti     180000  Diesel   First Owner

In [25]:
X_test_new=ohe.transform(X_test)

c:\Users\anshu\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [28]:
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(6502, 851), dtype=int32)